### ISSUE TITLE
Bug: callback isn't last argument

### ISSUE THREAD

**Issue by artdevgame** [overwolf/types#71]
I've recently been creating a promisify wrapper for overwolf API calls that relies on the callback being the last argument in a function definition, which I believe is the de facto way to use callbacks.

`openFilePicker` has two function definitions, one of them has `callback` as the third argument (rather than fourth):
https://github.com/overwolf/types/blob/4bea0f513b245fd946793ebfd87ae741bfc37d58/overwolf.d.ts#L5860-L5865

Can we make a breaking change update to keep a consistent interface?

**Comment by OdedItkinOW** [comment]
Hi!
Thank you for the report. However, we are aware that this method is a bit of an outlier, and while it is certainly something that can be considered a bug, it has already been out in the wild for far too long, and as such, we cannot change it gracefully.

That being said, even if we did, this wouldn't solve this issue fully. After all, there are functions out there in the API, that do not use callbacks. There are even functions that use *two* callbacks. And there are more weird oddities once you get into the nitty gritty of it. As such, and as much as it hurts me to say - there probably isn't one single generic solution that would work for all apis that you can use.

However, assuming you take a types definition file, you can, by all means, try and generate from that, a promisified file containing overrides for every method, which you can then manually tweak where necessary. This would most likely also be more future-proof

Hope this helps!
